version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    env_file:
      - .env # Explicitly load .env file for this service
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Prevent local node_modules from overwriting container's
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  test-client: # New service for the test client application
    image: node:18-alpine
    container_name: license-manager-test-client-1
    working_dir: /usr/src/app
    volumes:
      - ./test-client-app.js:/usr/src/app/test-client-app.js
    command: ["node", "test-client-app.js"]
    environment:
      - LICENSE_SERVER_URL=http://backend:4000 # 'backend' is the service name of your backend container
      - PROJECT_IDENTIFIER=test-project-001 # Example identifier, can be overridden
      # - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - backend
    restart: on-failure # Or unless-stopped, depending on how you want to manage it

  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL:-http://backend:4000/api}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    volumes:
      - ./frontend/src:/app/src # Mount only src for faster hot-reloading
      # For create-react-app, if you want to mount the entire frontend directory for easier Dockerfile changes without rebuilding:
      # - ./frontend:/app 
      # - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:4000/api} # Using service name 'backend' for inter-container communication
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped

  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-license_manager_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data # Data stored locally in ./data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-license_manager_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# Named volume 'license_manager_db_data' is no longer needed as we are using a bind mount. 